
/*WAP to print all male employee names?
WAP to print all female employee names?


/*WAP to print all employee names?*/
let employees=[{"id":1,"name":"Nissa","gender":"Female"},
{"id":2,"name":"Agustin","gender":"Male"},
{"id":3,"name":"Ethan","gender":"Male"},
{"id":4,"name":"Massimo","gender":"Male"},
{"id":5,"name":"Jarred","gender":"Male"},
{"id":6,"name":"Reagan","gender":"Male"},
{"id":7,"name":"Henriette","gender":"Female"},
{"id":8,"name":"Aveline","gender":"Female"},
{"id":9,"name":"Amity","gender":"Female"},
{"id":10,"name":"Raddy","gender":"Male"},
{"id":11,"name":"Padget","gender":"Male"},
{"id":12,"name":"Jo-anne","gender":"Female"},
{"id":13,"name":"Riki","gender":"Female"},
{"id":14,"name":"Bibbie","gender":"Female"},
{"id":15,"name":"Joye","gender":"Female"},
{"id":16,"name":"Wells","gender":"Male"},
{"id":17,"name":"Paige","gender":"Male"},
{"id":18,"name":"Grady","gender":"Male"},
{"id":19,"name":"Marijn","gender":"Male"},
{"id":20,"name":"Boycie","gender":"Male"},
{"id":21,"name":"Berthe","gender":"Female"},
{"id":22,"name":"Catlin","gender":"Female"},
{"id":23,"name":"Kandy","gender":"Female"},
{"id":24,"name":"Mureil","gender":"Genderfluid"},
{"id":25,"name":"Waylan","gender":"Male"},
{"id":26,"name":"Auberon","gender":"Male"},
{"id":27,"name":"Prudi","gender":"Female"},
{"id":28,"name":"Aigneis","gender":"Bigender"},
{"id":29,"name":"Rennie","gender":"Female"},
{"id":30,"name":"Tull","gender":"Male"},
{"id":31,"name":"Paulita","gender":"Female"},
{"id":32,"name":"Tamas","gender":"Male"},
{"id":33,"name":"Karrah","gender":"Non-binary"},
{"id":34,"name":"Katharina","gender":"Female"},
{"id":35,"name":"Tripp","gender":"Male"},
{"id":36,"name":"Rolfe","gender":"Male"},
{"id":37,"name":"Salli","gender":"Female"},
{"id":38,"name":"Ninnetta","gender":"Female"},
{"id":39,"name":"Lock","gender":"Male"},
{"id":40,"name":"Florenza","gender":"Female"},
{"id":41,"name":"Rosaline","gender":"Female"},
{"id":42,"name":"Dorthea","gender":"Female"},
{"id":43,"name":"Ardath","gender":"Female"},
{"id":44,"name":"Bert","gender":"Male"},
{"id":45,"name":"Kimberley","gender":"Female"},
{"id":46,"name":"Dinnie","gender":"Female"},
{"id":47,"name":"Leonie","gender":"Female"},
{"id":48,"name":"Hans","gender":"Male"},
{"id":49,"name":"Jerad","gender":"Genderqueer"},
{"id":50,"name":"Carola","gender":"Female"},
{"id":51,"name":"Antone","gender":"Male"},
{"id":52,"name":"Coleman","gender":"Male"},
{"id":53,"name":"Timi","gender":"Female"},
{"id":54,"name":"Felice","gender":"Male"},
{"id":55,"name":"Tiffanie","gender":"Female"},
{"id":56,"name":"Isa","gender":"Female"},
{"id":57,"name":"Dorothea","gender":"Female"},
{"id":58,"name":"Clarine","gender":"Female"},
{"id":59,"name":"Saxe","gender":"Genderqueer"},
{"id":60,"name":"Emmalynn","gender":"Female"},
{"id":61,"name":"Filmer","gender":"Male"},
{"id":62,"name":"Birk","gender":"Genderfluid"},
{"id":63,"name":"Ginger","gender":"Male"},
{"id":64,"name":"Jana","gender":"Female"},
{"id":65,"name":"Ernestine","gender":"Female"},
{"id":66,"name":"Truman","gender":"Male"},
{"id":67,"name":"Fielding","gender":"Male"},
{"id":68,"name":"Minny","gender":"Female"},
{"id":69,"name":"Levin","gender":"Male"},
{"id":70,"name":"Gae","gender":"Female"},
{"id":71,"name":"Ardene","gender":"Female"},
{"id":72,"name":"Perri","gender":"Female"},
{"id":73,"name":"Tanitansy","gender":"Female"},
{"id":74,"name":"Terrie","gender":"Female"},
{"id":75,"name":"Elvis","gender":"Male"},
{"id":76,"name":"Jennifer","gender":"Female"},
{"id":77,"name":"Maridel","gender":"Female"},
{"id":78,"name":"Prescott","gender":"Male"},
{"id":79,"name":"Kale","gender":"Male"},
{"id":80,"name":"Agathe","gender":"Non-binary"},
{"id":81,"name":"Lalo","gender":"Male"},
{"id":82,"name":"Elyssa","gender":"Female"},
{"id":83,"name":"Reginald","gender":"Male"},
{"id":84,"name":"Boone","gender":"Male"},
{"id":85,"name":"Jayson","gender":"Male"},
{"id":86,"name":"Gino","gender":"Male"},
{"id":87,"name":"Doris","gender":"Female"},
{"id":88,"name":"Kin","gender":"Male"},
{"id":89,"name":"Leila","gender":"Female"},
{"id":90,"name":"Vikki","gender":"Female"},
{"id":91,"name":"Hillard","gender":"Male"},
{"id":92,"name":"Patty","gender":"Female"},
{"id":93,"name":"Alanson","gender":"Male"},
{"id":94,"name":"Breena","gender":"Female"},
{"id":95,"name":"Timi","gender":"Female"},
{"id":96,"name":"Becka","gender":"Genderqueer"},
{"id":97,"name":"Vernor","gender":"Male"},
{"id":98,"name":"Layney","gender":"Female"},
{"id":99,"name":"Ester","gender":"Female"},
{"id":100,"name":"Egbert","gender":"Male"}]
for(let emp of employees){
    console.log(`Name:${emp.name} and gender-${emp.gender}`)
}


let users=[
    {uid:1,uname:"Rahul",gender:'Male'},
    {uid:2,uname:"Sonia",gender:'Female'},
    {uid:3,uname:"Priyanka",gender:'Female'},
    {uid:4,uname:"Modi",gender:'Male'},
    {uid:5,uname:"Amith",gender:'Male'},
    {uid:6,uname:"Salman",gender:'Male'},
]
//print all female users
for(let user of users){
    if(user.gender==="Female"){
        console.log(user.uname)
    }
}

/*WAP to print  no of female employee from employees?*/
let employee=[{"id":1,"name":"Nissa","gender":"Female"},
{"id":2,"name":"Agustin","gender":"Male"},
{"id":3,"name":"Ethan","gender":"Male"},
{"id":4,"name":"Massimo","gender":"Male"},
{"id":5,"name":"Jarred","gender":"Male"},
{"id":6,"name":"Reagan","gender":"Male"},
{"id":7,"name":"Henriette","gender":"Female"},
{"id":8,"name":"Aveline","gender":"Female"},
{"id":9,"name":"Amity","gender":"Female"},
{"id":10,"name":"Raddy","gender":"Male"},
{"id":11,"name":"Padget","gender":"Male"},
{"id":12,"name":"Jo-anne","gender":"Female"},
{"id":13,"name":"Riki","gender":"Female"},
{"id":14,"name":"Bibbie","gender":"Female"},
{"id":15,"name":"Joye","gender":"Female"},
{"id":16,"name":"Wells","gender":"Male"},
{"id":17,"name":"Paige","gender":"Male"},
{"id":18,"name":"Grady","gender":"Male"},
{"id":19,"name":"Marijn","gender":"Male"},
{"id":20,"name":"Boycie","gender":"Male"},
{"id":21,"name":"Berthe","gender":"Female"},
{"id":22,"name":"Catlin","gender":"Female"},
{"id":23,"name":"Kandy","gender":"Female"},
{"id":24,"name":"Mureil","gender":"Genderfluid"},
{"id":25,"name":"Waylan","gender":"Male"},
{"id":26,"name":"Auberon","gender":"Male"},
{"id":27,"name":"Prudi","gender":"Female"},
{"id":28,"name":"Aigneis","gender":"Bigender"},
{"id":29,"name":"Rennie","gender":"Female"},
{"id":30,"name":"Tull","gender":"Male"},
{"id":31,"name":"Paulita","gender":"Female"},
{"id":32,"name":"Tamas","gender":"Male"},
{"id":33,"name":"Karrah","gender":"Non-binary"},
{"id":34,"name":"Katharina","gender":"Female"},
{"id":35,"name":"Tripp","gender":"Male"},
{"id":36,"name":"Rolfe","gender":"Male"},
{"id":37,"name":"Salli","gender":"Female"},
{"id":38,"name":"Ninnetta","gender":"Female"},
{"id":39,"name":"Lock","gender":"Male"},
{"id":40,"name":"Florenza","gender":"Female"},
{"id":41,"name":"Rosaline","gender":"Female"},
{"id":42,"name":"Dorthea","gender":"Female"},
{"id":43,"name":"Ardath","gender":"Female"},
{"id":44,"name":"Bert","gender":"Male"},
{"id":45,"name":"Kimberley","gender":"Female"},
{"id":46,"name":"Dinnie","gender":"Female"},
{"id":47,"name":"Leonie","gender":"Female"},
{"id":48,"name":"Hans","gender":"Male"},
{"id":49,"name":"Jerad","gender":"Genderqueer"},
{"id":50,"name":"Carola","gender":"Female"},
{"id":51,"name":"Antone","gender":"Male"},
{"id":52,"name":"Coleman","gender":"Male"},
{"id":53,"name":"Timi","gender":"Female"},
{"id":54,"name":"Felice","gender":"Male"},
{"id":55,"name":"Tiffanie","gender":"Female"},
{"id":56,"name":"Isa","gender":"Female"},
{"id":57,"name":"Dorothea","gender":"Female"},
{"id":58,"name":"Clarine","gender":"Female"},
{"id":59,"name":"Saxe","gender":"Genderqueer"},
{"id":60,"name":"Emmalynn","gender":"Female"},
{"id":61,"name":"Filmer","gender":"Male"},
{"id":62,"name":"Birk","gender":"Genderfluid"},
{"id":63,"name":"Ginger","gender":"Male"},
{"id":64,"name":"Jana","gender":"Female"},
{"id":65,"name":"Ernestine","gender":"Female"},
{"id":66,"name":"Truman","gender":"Male"},
{"id":67,"name":"Fielding","gender":"Male"},
{"id":68,"name":"Minny","gender":"Female"},
{"id":69,"name":"Levin","gender":"Male"},
{"id":70,"name":"Gae","gender":"Female"},
{"id":71,"name":"Ardene","gender":"Female"},
{"id":72,"name":"Perri","gender":"Female"},
{"id":73,"name":"Tanitansy","gender":"Female"},
{"id":74,"name":"Terrie","gender":"Female"},
{"id":75,"name":"Elvis","gender":"Male"},
{"id":76,"name":"Jennifer","gender":"Female"},
{"id":77,"name":"Maridel","gender":"Female"},
{"id":78,"name":"Prescott","gender":"Male"},
{"id":79,"name":"Kale","gender":"Male"},
{"id":80,"name":"Agathe","gender":"Non-binary"},
{"id":81,"name":"Lalo","gender":"Male"},
{"id":82,"name":"Elyssa","gender":"Female"},
{"id":83,"name":"Reginald","gender":"Male"},
{"id":84,"name":"Boone","gender":"Male"},
{"id":85,"name":"Jayson","gender":"Male"},
{"id":86,"name":"Gino","gender":"Male"},
{"id":87,"name":"Doris","gender":"Female"},
{"id":88,"name":"Kin","gender":"Male"},
{"id":89,"name":"Leila","gender":"Female"},
{"id":90,"name":"Vikki","gender":"Female"},
{"id":91,"name":"Hillard","gender":"Male"},
{"id":92,"name":"Patty","gender":"Female"},
{"id":93,"name":"Alanson","gender":"Male"},
{"id":94,"name":"Breena","gender":"Female"},
{"id":95,"name":"Timi","gender":"Female"},
{"id":96,"name":"Becka","gender":"Genderqueer"},
{"id":97,"name":"Vernor","gender":"Male"},
{"id":98,"name":"Layney","gender":"Female"},
{"id":99,"name":"Ester","gender":"Female"},
{"id":100,"name":"Egbert","gender":"Male"}]
let no_female_emps=0
for(let emp of employee){
     if(emp.gender==="Female"){
        no_female_emps++;
     }
}
console.log("No of female employees:-",no_female_emps)

/*WAP to print  no of male employee from employees?*/
let user=[
    {uid:1,uname:"Rahul",gender:'Male'},
    {uid:2,uname:"Sonia",gender:'Female'},
    {uid:3,uname:"Priyanka",gender:'Female'},
    {uid:4,uname:"Modi",gender:'Male'},
    {uid:5,uname:"Amith",gender:'Male'},
    {uid:6,uname:"Salman",gender:'Male'},
]
let no_male_users=0
for(let i=0;i<=user.length-1;i++){
    if(user [i].gender==="Male"){
        no_male_users=no_male_users+1;
    }
}
console.log("No of male employees:-",no_male_users)
